# Generated by Django 4.0 on 2022-03-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actype', models.CharField(choices=[('Saving', 'Saving'), ('current', 'current'), ('Fixed', 'fixed')], max_length=200, null=True)),
                ('branch', models.CharField(choices=[('Latur', 'Latur'), ('Barshi', 'Barshi'), ('Pune', 'Pune'), ('Nanded', 'Nanded'), ('Ausa', 'Ausa')], max_length=200, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
