# Generated by Django 4.0 on 2022-03-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='acno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='accountno',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount'),
        ),
    ]
