# Generated by Django 4.0 on 2022-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_acno_transaction_accountno'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='actype',
            field=models.CharField(choices=[('Saving', 'Saving'), ('current', 'current'), ('Fixed', 'Fixed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='curr_balance',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
