# Generated by Django 4.0 on 2022-03-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_amount_alter_bankaccount_actype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='username',
            new_name='recivername',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sendername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
