# Generated by Django 4.0 on 2022-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_username_transaction_recivername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='acno',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='curr_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sendername',
        ),
        migrations.AddField(
            model_name='user',
            name='curr_balance',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
