# Generated by Django 4.0 on 2022-03-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_transaction_acno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curr_balance',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='curr_balance',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
