# Generated by Django 4.0 on 2022-03-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_curr_balance_bankaccount_curr_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('accountno', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankaccount')),
                ('recivername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
